dirs.src = "src"       # The src directory contains all non-static site content.
dirs.out = "out"       # The out directory is where the generated site is written to.
dirs.static = "static" # Content in the static directory is copied as-is to the out directory.
dirs.layout = "layout" # The layout directory is where layouts live.

# The contents of the data section are made available in template rendering.
[data]
site.title = "~alterae"

[data.page_titles]
# TODO: refactor these to be segmented arrays
"src/index.html" = ""
"src/colophon.html" = " / Colophon"
"src/404.html" = " / 404"
"src/blog/index.html" = " / Blog"
"src/blog/mksite.html" = "/ Blog / Another Static Site Generator"

# Transforms are used to further transform content after applying templating.
[transforms]
# md.html = "pandoc -f markdown -t html"
